services:
  app:
    image: nginx:alpine
    container_name: lime
    restart: unless-stopped
    volumes:
      - ./web:/usr/share/nginx/html
      - ../cdn:/usr/share/nginx/html/cdn:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8080:80"
